# Generated by Django 3.1.2 on 2020-10-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='opciones',
            field=models.ManyToManyField(blank=True, to='api.Opcion'),
        ),
    ]
