# Generated by Django 3.1.2 on 2020-10-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201008_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['-id']},
        ),
    ]
